package vues;

import bdd.Base;
import bdd.BureauDeVote;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import services.ElecteurService;

/**
 *
 * @author Olivier Guillaume
 */
public class pElecteurs extends javax.swing.JPanel {
    private final Base base=new Base();
    /**
     * Creates new form pElecteurs (Panneau Electeurs)
     */
    public pElecteurs() {
        initComponents();
    }

    public JTable getjTableElecteur() {
        return jTableElecteur;
    }

    public JComboBox getjBoxBureau() {
        return jBoxBureau;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNomElect = new javax.swing.JTextField();
        jPrenomElect = new javax.swing.JTextField();
        jAdresse = new javax.swing.JTextField();
        jLabelNomElect = new javax.swing.JLabel();
        jLabelPrenomElect = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableElecteur = new javax.swing.JTable();
        jLabelAdresse = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelBureau = new javax.swing.JLabel();
        jBoxBureau = new javax.swing.JComboBox();
        AnnulerBoutonE = new javax.swing.JButton();
        jLabelIdent = new javax.swing.JLabel();
        jIdentifiant = new javax.swing.JTextField();
        AjouterBoutonE = new javax.swing.JButton();
        jLabelPasse = new javax.swing.JLabel();
        jPassword = new javax.swing.JTextField();
        ModifierBoutonE = new javax.swing.JButton();
        RetireBoutonE = new javax.swing.JButton();
        jLabelForme = new javax.swing.JLabel();
        jIdElecteur = new javax.swing.JLabel();
        jTextJour = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextMois = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextAnnee = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 255, 153));
        setPreferredSize(new java.awt.Dimension(650, 300));

        jLabelNomElect.setText("Nom");

        jLabelPrenomElect.setText("Prenom");

        jTableElecteur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Prenom", "Adresse", "DateNaissance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableElecteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableElecteurMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableElecteur);

        jLabelAdresse.setText("Adresse");

        jLabelDate.setText("Date de naissance");

        jLabelBureau.setText("Bureau");

        jBoxBureau.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "bureau" }));
        jBoxBureau.setToolTipText("essai");

        AnnulerBoutonE.setBackground(new java.awt.Color(255, 51, 51));
        AnnulerBoutonE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Arreter.jpg"))); // NOI18N
        AnnulerBoutonE.setText("Annuler");
        AnnulerBoutonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerBoutonEActionPerformed(evt);
            }
        });

        jLabelIdent.setText("Identifiant");

        AjouterBoutonE.setBackground(new java.awt.Color(102, 255, 102));
        AjouterBoutonE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Lancer.jpg"))); // NOI18N
        AjouterBoutonE.setText("Ajouter");
        AjouterBoutonE.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        AjouterBoutonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterBoutonEActionPerformed(evt);
            }
        });

        jLabelPasse.setText("Passe");

        ModifierBoutonE.setBackground(new java.awt.Color(102, 102, 255));
        ModifierBoutonE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Etoile.jpg"))); // NOI18N
        ModifierBoutonE.setText("Modifier");
        ModifierBoutonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierBoutonEActionPerformed(evt);
            }
        });

        RetireBoutonE.setBackground(new java.awt.Color(255, 153, 0));
        RetireBoutonE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Rond.jpg"))); // NOI18N
        RetireBoutonE.setText("Retirer");
        RetireBoutonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetireBoutonEActionPerformed(evt);
            }
        });

        jLabelForme.setText("JJ/MM/AAAA");

        jTextJour.setText("__");

        jLabel3.setText("/");

        jTextMois.setText("__");

        jLabel4.setText("/");

        jTextAnnee.setText("____");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPasse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelIdent))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(ModifierBoutonE)
                                        .addGap(18, 18, 18)
                                        .addComponent(RetireBoutonE))
                                    .addComponent(jBoxBureau, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(AjouterBoutonE)))
                        .addGap(18, 18, 18)
                        .addComponent(AnnulerBoutonE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBureau)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAdresse)
                                    .addComponent(jLabelPrenomElect, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNomElect))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNomElect, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPrenomElect, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelForme)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(358, 358, 358)
                    .addComponent(jIdElecteur)
                    .addContainerGap(443, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAdresse)
                                .addGap(42, 42, 42))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPrenomElect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNomElect))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jNomElect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPrenomElect, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelForme)
                                    .addComponent(jTextMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDate)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIdent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPasse, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBureau)
                            .addComponent(jBoxBureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjouterBoutonE)
                    .addComponent(ModifierBoutonE)
                    .addComponent(RetireBoutonE)
                    .addComponent(AnnulerBoutonE))
                .addGap(78, 78, 78))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(jIdElecteur)
                    .addContainerGap(192, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableElecteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableElecteurMouseClicked
        int numeroLigne =jTableElecteur.getSelectedRow();
        int idElecteur=(int)jTableElecteur.getValueAt(numeroLigne, 0);
        String nom=(String)jTableElecteur.getValueAt(numeroLigne, 1);
        String prenom=(String)jTableElecteur.getValueAt(numeroLigne, 2);
        String adresse=(String)jTableElecteur.getValueAt(numeroLigne, 3);
        String date=(String)jTableElecteur.getValueAt(numeroLigne, 4);
        jNomElect.setText(nom);
        jPrenomElect.setText(prenom);
        jAdresse.setText(adresse);
        jTextJour.setText(date.split("/")[0]);
        jTextMois.setText(date.split("/")[1]);
        jTextAnnee.setText(date.split("/")[2]);
        jIdElecteur.setVisible(false);
        jIdElecteur.setText(String.valueOf(idElecteur));
    }//GEN-LAST:event_jTableElecteurMouseClicked

    private void AnnulerBoutonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerBoutonEActionPerformed
        /*     Vue choixvue =new VueChoix();// arevoir
        this.dispose();
        choixvue.show();*/
    }//GEN-LAST:event_AnnulerBoutonEActionPerformed

    private void AjouterBoutonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterBoutonEActionPerformed
        ElecteurService serviceElecteur = new ElecteurService();
        try {
            Connection connexion = base.connexion();
            // recupération des champs
            BureauDeVote bureauSelectionne=(BureauDeVote) this.jBoxBureau.getSelectedItem();
            int idBureau = bureauSelectionne.getNumBureau();
            String nom=jNomElect.getText();
            String prenom=jPrenomElect.getText();
            //recup de la date depuis les champ jFieldJour/Mois/Annee en mode String
            String jour= jTextJour.getText();
            String mois=jTextMois.getText();
            String annee=jTextAnnee.getText();
            if(!VueAdministration.controleDate(jour, mois, annee,false)){
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog( null,"La date est incorrecte (<1900 ou >aujourd'hui).",
                    "Attention!" ,
                    JOptionPane.WARNING_MESSAGE );
            } else{
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                String datenaiss=formatter.format( jour+"/"+mois+"/"+annee);
                System.out.println("date:"+datenaiss);
                // recup de la date en mode java.util.date
                java.util.Date date = formatter.parse(jour+"/"+mois+"/"+annee);
                // génération de l'identifiant automatique
                jIdentifiant.setText(serviceElecteur.creerIdentifiant(nom, prenom, datenaiss));
                // conversion java.util.Date -> java.sql.Date pour la BDD
                java.sql.Date dateNaissance=VueAdministration.convertUtiltoSQLDate(date);
                // génération du mot de passe automatique sécurisé
                jPassword.setText(serviceElecteur.creerMotDePasse(10));
                serviceElecteur.creerElecteur(connexion,nom, prenom,
                    jAdresse.getText(), jPassword.getText(), idBureau, jIdentifiant.getText(), dateNaissance);
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog( null, "L'électeur(trice)"+nom+" "+prenom+" a bien été créé(e)",
                    "Confirmation",
                    JOptionPane.INFORMATION_MESSAGE );}
            base.deconnexion(connexion);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VueAdministration.class.getName()).log(Level.SEVERE, "pb connexion", ex);
        } catch (ParseException ex) {
            Logger.getLogger(VueAdministration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AjouterBoutonEActionPerformed

    private void ModifierBoutonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierBoutonEActionPerformed
        ElecteurService serviceElecteur = new ElecteurService();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Connection connexion = base.connexion();
            // recupération des champs
            BureauDeVote bureauSelectionne=(BureauDeVote) this.jBoxBureau.getSelectedItem();
            int idBureau = bureauSelectionne.getNumBureau();
            String nom=jNomElect.getText();
            String prenom=jPrenomElect.getText();
            System.out.println("nom="+nom+" "+prenom);
            // recup de la date en mode java.util.date
            String jour= jTextJour.getText();
            String mois=jTextMois.getText();
            String annee=jTextAnnee.getText();
            if(!VueAdministration.controleDate(jour, mois, annee,false)){
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog( null, "La date est incorrecte (<1900 ou >aujourd'hui)",
                    "Attention!",
                    JOptionPane.WARNING_MESSAGE );
            }else{
                java.util.Date date = formatter.parse(jour+"/"+mois+"/"+annee);
                // génération de l'identifiant automatique
                jIdentifiant.setText(serviceElecteur.creerIdentifiant(nom, prenom,jour+"/"+mois+"/"+annee));
                // conversion java.util.Date -> java.sql.Date pour la BDD
                java.sql.Date dateNaissance=VueAdministration.convertUtiltoSQLDate(date);
                // le mot de passe est conservé
                int idElecteur=Integer.parseInt(jIdElecteur.getText());

                serviceElecteur.modifierElecteur(connexion, idElecteur,nom,prenom,jAdresse.getText(),
                    idBureau,jIdentifiant.getText(),dateNaissance);
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog( null, "L'électeur(trice)"+nom+" "+prenom+" a bien été modifié(e)",
                    "Confirmation!",
                    JOptionPane.INFORMATION_MESSAGE );}
            base.deconnexion(connexion);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VueAdministration.class.getName()).log(Level.SEVERE, "pb de connexion", ex);
        } catch (ParseException ex) {
            Logger.getLogger(VueAdministration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ModifierBoutonEActionPerformed

    private void RetireBoutonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetireBoutonEActionPerformed
        try {
            Connection connexion = base.connexion();
            ElecteurService serviceElecteur = new ElecteurService();
            // on recupere l'id dans la table
            int id=jTableElecteur.getSelectedRow();
            serviceElecteur.retirerElecteur(connexion, id);
            base.deconnexion(connexion);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VueAdministration.class.getName()).log(Level.SEVERE, "pb de connexion", ex);
        }
    }//GEN-LAST:event_RetireBoutonEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterBoutonE;
    private javax.swing.JButton AnnulerBoutonE;
    private javax.swing.JButton ModifierBoutonE;
    private javax.swing.JButton RetireBoutonE;
    private javax.swing.JTextField jAdresse;
    private javax.swing.JComboBox jBoxBureau;
    private javax.swing.JLabel jIdElecteur;
    private javax.swing.JTextField jIdentifiant;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelBureau;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelForme;
    private javax.swing.JLabel jLabelIdent;
    private javax.swing.JLabel jLabelNomElect;
    private javax.swing.JLabel jLabelPasse;
    private javax.swing.JLabel jLabelPrenomElect;
    private javax.swing.JTextField jNomElect;
    private javax.swing.JTextField jPassword;
    private javax.swing.JTextField jPrenomElect;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableElecteur;
    private javax.swing.JTextField jTextAnnee;
    private javax.swing.JTextField jTextJour;
    private javax.swing.JTextField jTextMois;
    // End of variables declaration//GEN-END:variables
}
