/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import bdd.Base;
import bdd.BureauDeVote;
import bdd.Election;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import services.BureauService;
import services.ElectionService;
import services.RelationEBVService;
import static vues.VueAdministration.controleDate;
import static vues.VueAdministration.convertUtiltoSQLDate;

/**
 *
 * @author adm
 */
public class pElections extends javax.swing.JPanel {
    private final Base base = new Base();
    /**
     * Creates new form pElections
     */
    public pElections() {
        initComponents();
    }

    public JTable getjTableElection() {
        return jTableElection;
    }

    public JList getjListeBureaux() {
        return jListeBureaux;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNomScrutin = new javax.swing.JTextField();
        jLabelType = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListeBureaux = new javax.swing.JList();
        jLabelDateScrutin = new javax.swing.JLabel();
        jType = new javax.swing.JTextField();
        jLabelListeBureau = new javax.swing.JLabel();
        RetirerBoutonL = new javax.swing.JButton();
        ModifierBoutonL = new javax.swing.JButton();
        AnnulerBoutonL = new javax.swing.JButton();
        AjouterBoutonL = new javax.swing.JButton();
        jLabelFormat = new javax.swing.JLabel();
        jLabelScrutin = new javax.swing.JLabel();
        jIdElection = new javax.swing.JLabel();
        jTextJourElection = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextMoisElection = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextAnneeElection = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableElection = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 153, 255));
        setPreferredSize(new java.awt.Dimension(650, 300));

        jLabelType.setText("Type");

        jScrollPane5.setViewportView(jListeBureaux);

        jLabelDateScrutin.setText("Date");

        jLabelListeBureau.setText("Bureaux");

        RetirerBoutonL.setBackground(new java.awt.Color(255, 153, 0));
        RetirerBoutonL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Rond.jpg"))); // NOI18N
        RetirerBoutonL.setText("Retirer");
        RetirerBoutonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirerBoutonLActionPerformed(evt);
            }
        });

        ModifierBoutonL.setBackground(new java.awt.Color(102, 102, 255));
        ModifierBoutonL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Etoile.jpg"))); // NOI18N
        ModifierBoutonL.setText("Modifier");
        ModifierBoutonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierBoutonLActionPerformed(evt);
            }
        });

        AnnulerBoutonL.setBackground(new java.awt.Color(255, 51, 51));
        AnnulerBoutonL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Arreter.jpg"))); // NOI18N
        AnnulerBoutonL.setText("Retour");
        AnnulerBoutonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerBoutonLActionPerformed(evt);
            }
        });

        AjouterBoutonL.setBackground(new java.awt.Color(102, 255, 102));
        AjouterBoutonL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Lancer.jpg"))); // NOI18N
        AjouterBoutonL.setText("Ajouter");
        AjouterBoutonL.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AjouterBoutonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterBoutonLActionPerformed(evt);
            }
        });

        jLabelFormat.setText("JJ/MM/AAAA");

        jLabelScrutin.setText("Nom");

        jTextJourElection.setText("__");

        jLabel5.setText("/");

        jTextMoisElection.setText("__");

        jLabel6.setText("/");

        jTextAnneeElection.setText("____");

        jTableElection.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Type", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableElection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableElectionMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableElection);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelScrutin)
                                .addGap(22, 22, 22)
                                .addComponent(jNomScrutin, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelListeBureau)
                                    .addComponent(jLabelDateScrutin)
                                    .addComponent(jLabelType))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jTextJourElection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextMoisElection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextAnneeElection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelFormat))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(AjouterBoutonL)
                        .addGap(28, 28, 28)
                        .addComponent(ModifierBoutonL)
                        .addGap(39, 39, 39)
                        .addComponent(RetirerBoutonL)
                        .addGap(27, 27, 27)
                        .addComponent(AnnulerBoutonL, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(358, 358, 358)
                    .addComponent(jIdElection)
                    .addContainerGap(685, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNomScrutin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelScrutin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelType)
                            .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDateScrutin)
                            .addComponent(jTextJourElection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTextMoisElection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextAnneeElection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFormat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelListeBureau)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjouterBoutonL)
                    .addComponent(ModifierBoutonL)
                    .addComponent(RetirerBoutonL)
                    .addComponent(AnnulerBoutonL))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(jIdElection)
                    .addContainerGap(275, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableElectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableElectionMouseClicked
        int numeroLigne=jTableElection.getSelectedRow();
        int idElection=(int)jTableElection.getValueAt(numeroLigne, 0);
        String nom=(String)jTableElection.getValueAt(numeroLigne, 1);
        String type=(String)jTableElection.getValueAt(numeroLigne,2);
        String date=(String)jTableElection.getValueAt(numeroLigne, 3);
        jNomScrutin.setText(nom);
        jType.setText(type);
        jIdElection.setVisible(false);
        jIdElection.setText(String.valueOf(idElection));
        jTextJourElection.setText(date.split("/")[0]);
        jTextMoisElection.setText(date.split("/")[1]);
        jTextAnneeElection.setText(date.split("/")[2]);
    }//GEN-LAST:event_jTableElectionMouseClicked

    private void RetirerBoutonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirerBoutonLActionPerformed
        try {
            Connection connexion = base.connexion();
            ElectionService serviceElection = new ElectionService();
            // on recupere l'id dans la table
            int id=jTableElection.getSelectedRow();
            serviceElection.retirerElection(connexion, id);
            base.deconnexion(connexion);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VueAdministration.class.getName()).log(Level.SEVERE, "pb de connexion", ex);
        }
    }//GEN-LAST:event_RetirerBoutonLActionPerformed

    private void ModifierBoutonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierBoutonLActionPerformed
        ElectionService serviceElection = new ElectionService();
        BureauService serviceBureau = new BureauService();
        try {
            Connection connexion = base.connexion();
            //recupération des champs
            String type = jType.getText();
            String scrutin = jNomScrutin.getText();
            System.out.println("type: "+type+";nom="+scrutin);
            int idElection=Integer.parseInt(jIdElection.getText());
            String jour= jTextJourElection.getText();
            String mois=jTextMoisElection.getText();
            String annee=jTextAnneeElection.getText();
            if(!controleDate(jour, mois, annee,true)){
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog( null, "La date est incorrecte (<1900 ou >aujourd'hui)",
                    "Attention !",
                    JOptionPane.WARNING_MESSAGE );
            } else{
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                // recup de la date en mode java.util.date
                java.util.Date dateScrutin = formatter.parse(jour+"/"+mois+"/"+annee);
                List<String> listeBUrSelection=jListeBureaux.getSelectedValuesList();
                List<BureauDeVote> listeBureauxSelectionnes = new ArrayList<BureauDeVote>();
                //creation de la liste des bureaux selectionnes
                for(Integer i=0;i<listeBUrSelection.size();i++){
                    System.out.println("element"+i+" :"+listeBUrSelection.get(i));
                    Integer numero=Integer.parseInt(listeBUrSelection.get(i).split(" ")[0]);
                    System.out.println("num="+numero);
                    BureauDeVote bureauElection=serviceBureau.chargerBureau(connexion,numero);
                    listeBureauxSelectionnes.add(bureauElection);
                }
                // conversion java.util.Date -> java.sql.Date pour la BDD
                java.sql.Date dateElection=convertUtiltoSQLDate(dateScrutin);
                Election electionModifiee=serviceElection.modifierElection(connexion, idElection, mois, type, dateElection);
                //chargement de la liste des bureaux de vote choisis
                electionModifiee.setBureauVoteCollection(listeBureauxSelectionnes);
                for(BureauDeVote bur : electionModifiee.getBureauVoteCollection()){
                    String nomBureauChoisi=bur.getLibelle();
                    System.out.println("elction :"+electionModifiee.getNom()+" dans le bureau "+nomBureauChoisi);
                }
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog( null, "L'élection "+electionModifiee.getNom()+" a été modifiée avec succès!",
                    "Confirmation !",
                    JOptionPane.INFORMATION_MESSAGE );
            }
            base.deconnexion(connexion);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VueAdministration.class.getName()).log(Level.SEVERE, "pb connexion", ex);
        } catch (ParseException ex) {
            Logger.getLogger(VueAdministration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ModifierBoutonLActionPerformed

    private void AnnulerBoutonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerBoutonLActionPerformed
        /*   VueChoix choixvue =new VueChoix();
        this.dispose();
        choixvue.show();*/
    }//GEN-LAST:event_AnnulerBoutonLActionPerformed

    private void AjouterBoutonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterBoutonLActionPerformed
        ElectionService serviceElection = new ElectionService();
        BureauService serviceBureau = new BureauService();
        try {
            Connection connexion = base.connexion();
            String type = jType.getText();
            String scrutin = jNomScrutin.getText();
            System.out.println("type: "+type+";nom="+scrutin);
            String jour= jTextJourElection.getText();
            String mois=jTextMoisElection.getText();
            String annee=jTextAnneeElection.getText();
            if(!controleDate(jour, mois, annee,true)){
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog( null, "La date est incorrecte (<1900 ou >aujourd'hui",
                    "Attention !",
                    JOptionPane.WARNING_MESSAGE );
            } else{
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                // recup de la date en mode java.util.date
                java.util.Date dateScrutin = formatter.parse(jour+"/"+mois+"/"+annee);
                List<String> listeBUrSelection=jListeBureaux.getSelectedValuesList();
                List<BureauDeVote> listeBureauxSelectionnes = new ArrayList<BureauDeVote>();
                //creation de la liste des bureaux selectionnes
                for(Integer i=0;i<listeBUrSelection.size();i++){
                    System.out.println("element"+i+" :"+listeBUrSelection.get(i));
                    Integer numero=Integer.parseInt(listeBUrSelection.get(i).split(" ")[0]);
                    System.out.println("num="+numero);
                    BureauDeVote bureauElection=serviceBureau.chargerBureau(connexion,numero);
                    listeBureauxSelectionnes.add(bureauElection);
                }
                // conversion java.util.Date -> java.sql.Date pour la BDD
                java.sql.Date dateElection=convertUtiltoSQLDate(dateScrutin);
                int idElection=serviceElection.creerElection(connexion, scrutin, type, dateElection);  
                Election electionCreee=serviceElection.chargerElection(connexion, idElection);
                //chargement de la liste des bureaux de vote choisis
                electionCreee.setBureauVoteCollection(listeBureauxSelectionnes);
                ///  ajout la liste des id bureaux
                RelationEBVService relation = new RelationEBVService();
                for(BureauDeVote bur : electionCreee.getBureauVoteCollection()){
                    relation.ajouterBureauAElection(idElection, bur.getNumBureau());
                }
                for(BureauDeVote bur : electionCreee.getBureauVoteCollection()){
                    String nomBureauChoisi=bur.getLibelle();
                    System.out.println("elction :"+electionCreee.getNom()+" dans le bureau "+nomBureauChoisi);
                }
            }
            base.deconnexion(connexion);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VueAdministration.class.getName()).log(Level.SEVERE, "pb connexion", ex);
        } catch (ParseException ex) {
            Logger.getLogger(VueAdministration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AjouterBoutonLActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterBoutonL;
    private javax.swing.JButton AnnulerBoutonL;
    private javax.swing.JButton ModifierBoutonL;
    private javax.swing.JButton RetirerBoutonL;
    private javax.swing.JLabel jIdElection;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDateScrutin;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JLabel jLabelListeBureau;
    private javax.swing.JLabel jLabelScrutin;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JList jListeBureaux;
    private javax.swing.JTextField jNomScrutin;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableElection;
    private javax.swing.JTextField jTextAnneeElection;
    private javax.swing.JTextField jTextJourElection;
    private javax.swing.JTextField jTextMoisElection;
    private javax.swing.JTextField jType;
    // End of variables declaration//GEN-END:variables
}
