/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import bdd.Base;
import bdd.BureauDeVote;
import bdd.Election;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import services.ResultatService;

/**
 *
 * @author adm
 */
public class pResultats extends javax.swing.JPanel {
    private final Base base = new Base();
    /**
     * Creates new form pResultats
     */
    public pResultats() {
        initComponents();
    }

    public JComboBox getjComboBoxBureau() {
        return jComboBoxBureau;
    }

    public JComboBox getjComboBoxElection() {
        return jComboBoxElection;
    }

    public JTable getjTableResultats() {
        return jTableResultats;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxElection = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultats = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableBureau = new javax.swing.JTable();
        jComboBoxBureau = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButtonChercher = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 51, 255));
        setPreferredSize(new java.awt.Dimension(650, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Election");

        jComboBoxElection.setBackground(new java.awt.Color(204, 204, 0));
        jComboBoxElection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "election" }));

        jTableResultats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Place", "Nom", "Nbre voix", "%"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableResultats);

        jTableBureau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inscrits", "Votants", "Exprimés"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTableBureau);

        jComboBoxBureau.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bureau de vote" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bureau");

        jButtonChercher.setBackground(new java.awt.Color(153, 255, 153));
        jButtonChercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Lancer.jpg"))); // NOI18N
        jButtonChercher.setText("Chercher");
        jButtonChercher.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonChercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonChercherMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxBureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxElection, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonChercher))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxElection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxBureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonChercher)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChercherMouseClicked
        Election electionSelectionnee=(Election) jComboBoxElection.getSelectedItem();
        int idElection=electionSelectionnee.getIdElection();
        BureauDeVote bureauSelectionne=(BureauDeVote) jComboBoxBureau.getSelectedItem();
        int idBureauS = bureauSelectionne.getNumBureau();
        ResultatService serviceResultat = new ResultatService();
        DefaultTableModel table = (DefaultTableModel) jTableResultats.getModel();
        for(int i=table.getRowCount();i>0;--i) table.removeRow(i-1);
        DefaultTableModel tableBureau=(DefaultTableModel)jTableBureau.getModel();
        for(int i=tableBureau.getRowCount();i>0;--i) tableBureau.removeRow(i-1);
        try{
            Connection connexion = base.connexion();
            List<List<String>> resultats = serviceResultat.recupererResultatsElection(connexion);
            //TO DO choisir résultats selon élection et bureau
            int nbInscrits=serviceResultat.nombreInscrits(connexion);
            int nbVotants=serviceResultat.nombreVotants(connexion);
            
            for(int i=0;i<resultats.size();i++){
                int id = Integer.parseInt(resultats.get(i).get(0));
                String nom = resultats.get(i).get(1);
                int nbVoix=Integer.parseInt(resultats.get(i).get(2));
                System.out.println("nbInscrits="+nbInscrits);
                float percent=((float)nbVoix)/((float)nbInscrits)*100;
                System.out.println("nbVoix/nbInscrits="+(float)(nbVoix/nbInscrits));
                Object[] row ={id,nom,nbVoix,percent};
                table.addRow(row);
            }
            Object[] row1={nbInscrits,nbVotants,null};
            tableBureau.addRow(row1);
        base.deconnexion(connexion);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(VueAdministration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonChercherMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChercher;
    private javax.swing.JComboBox jComboBoxBureau;
    private javax.swing.JComboBox jComboBoxElection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTableBureau;
    private javax.swing.JTable jTableResultats;
    // End of variables declaration//GEN-END:variables
}
